[[main]]
  name = "Log Hours"
  url = "https://www.trackitforward.com/site/rosedale-community-garden"
  weight = -109

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Member Info"
  identifier = "MemberInfoParent"
  weight = -108
[[main]]
  parent = "MemberInfoParent"
  name = "Garden Map"
  url = "#"
[[main]]
  parent = "MemberInfoParent"
  name = "Member Roster"
  url = "#"
[[main]]
  parent = "MemberInfoParent"
  name = "Project Teams"
  url = "#"
[[main]]
  parent = "MemberInfoParent"
  name = "Straw"
  url = "#"
[[main]]
  parent = "MemberInfoParent"
  name = "Tools"
  url = "#"
[[main]]
  parent = "MemberInfoParent"
  name = "Event Planning"
  url = "#"
[[main]]
  parent = "MemberInfoParent"
  name = "Reimbursement"
  url = "#"
[[main]]
  parent = "MemberInfoParent"
  name = "Finances"
  url = "#"


[[main]]
  name = "Garden Teams"
  identifier = "GardenTeamsParent"
  weight = -107
[[main]]
  parent = "GardenTeamsParent"
  name = "Bees"
  url = "#"
[[main]]
  parent = "GardenTeamsParent"
  name = "Orchard"
  url = "#"
[[main]]
  parent = "GardenTeamsParent"
  name = "Bokashi"
  url = "#"
[[main]]
  parent = "GardenTeamsParent"
  name = "Community Flower Station"
  url = "#"
[[main]]
  parent = "GardenTeamsParent"
  name = "Garlic"
  url = "#"


[[main]]
  name = "Pest Management"
  identifier = "PestManagementParent"
  weight = -106
[[main]]
  parent = "PestManagementParent"
  name = "Early Tomato Blight"
  url = "pest-management/early-tomato-blight/"
[[main]]
  parent = "PestManagementParent"
  name = "Japanese Beetles"
  url = "pest-management/japanese-beetles/"
[[main]]
  parent = "PestManagementParent"
  name = "Garlic Fire Spray"
  url = "pest-management/garlic-fire-spray/"
[[main]]
  parent = "PestManagementParent"
  name = "Puncturevine (Goat Head)"
  url = "pest-management/puncturevine-goat-head/"
[[main]]
  parent = "PestManagementParent"
  name = "Noxious vs Annoying Weeds"
  url = "pest-management/noxious-vs-annoying-weeds/"

[[main]]
  name = "Contact"
  url = "contact-us/"
  weight = -105



# social menu links
[[social]]
  #name = "github"
  #type = "social"
  #weight = 1
  #url = "https://github.com/rosedale-community-garden"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"
# name = "bluesky"
# url = "https://bsky.app/profile/#"